version: '3.8'

services:

  postgres:
      restart: always
      image: postgres
      ports:
        - 5432:5432
      env_file:
          - .env
      volumes:
        - database-data:/var/lib/postgresql/data/
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

  cicekbasket:
    image: 'cicekbasket'
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    
volumes:
    database-data: